name: CI - Mental Wellness App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports: ['27017:27017']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 👉 Install Server Dependencies
    - name: Install server dependencies
      run: |
        cd server
        npm install

    - name: Run backend tests (optional)
      run: |
        cd server
        npm test || echo "No backend tests yet"

    # 👉 Install Client Dependencies
    - name: Install client dependencies
      run: |
        cd client
        npm install

    - name: Build frontend
      run: |
        cd client
        npm run build
